config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "usuarios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :tipo_persona, :nombre, :tipo_documento, :identificacion, :f_emision, :f_vencimiento, :correo, :tlf_principal, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
        if @usuario.save
          format.html { redirect_to usuario_url(@usuario), notice: "Usuario a sido creado con exito!" }
          format.json { render :show, status: :created, location: @usuario }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @usuario.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario a sido modificado con exito!" }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario a sido eliminado!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:tipo_persona, :nombre, :tipo_documento, :identificacion, :f_emision, :f_vencimiento, :correo, :tlf_principal, :tlf_secundario)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" type="image/png" href="<%= asset_path('sisco.png') %>">
    <title>Sisco Bank C.A.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/usuarios/_form.html.erb
<center>
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "errores") %> encontrados </h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.attribute %> en blanco</li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label>Tipo de Persona</label><br>
    <%= form.select :tipo_persona, options_for_select([['Juridica', "Juridica"], ['Natural', "Natural"]]) %>
  </div>

  <div>
    <label>Nombre y apellido</label><br>
    <%= form.text_field :nombre, pattern: "([A-Za-z ]+)", title: "Solo se requieren letras en este campo" %>
  </div>

  <div>
    <label>Identificacion</label><br>
    <%= form.select :tipo_documento, options_for_select([['V-', "Venezolano"], ['P-', "Pasaporte"], ['R-', "Rif de Empresa"]]) %>
    <%= form.text_field :identificacion, pattern: "([0-9]+)", title: "Solo se requieren numeros en este campo" %>
  </div>

  <div>
    <label>Fecha de emision del documento de identificacion</label><br>
    <%= form.date_field :f_emision %>
  </div>

  <div>
    <label>Fecha de vencimiento del documento de identificacion</label><br>
    <%= form.date_field :f_vencimiento %>
  </div>

  <div>
    <label>Correo</label><br>
    <%= form.text_field :correo %>
  </div>

  <div>
    <label>Telefono principal</label><br>
    <%= form.text_field :tlf_principal, pattern: "([0-9]+)", title: "Solo se requieren numeros en este campo", value: "0" %>
  </div>

  <div>
    <label>Telefono secundario</label><br>
    <%= form.text_field :tlf_secundario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</center>

app/views/usuarios/_usuario.html.erb
<center>
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Tipo persona:</strong>
    <%= usuario.tipo_persona %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= usuario.nombre %>
  </p>

  <p>
    <strong>Tipo de documento:</strong>
    <%= usuario.tipo_documento %>
  </p>

  <p>
    <strong>Identificacion:</strong>
    <%= usuario.identificacion %>
  </p>

  <p>
    <strong>Fecha emision identificacion:</strong>
    <%= usuario.f_emision %>
  </p>

  <p>
    <strong>Fechas vencimiento identificacion:</strong>
    <%= usuario.f_vencimiento %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= usuario.correo %>
  </p>

  <p>
    <strong>Telefono principal:</strong>
    <%= usuario.tlf_principal %>
  </p>

  <p>
    <strong>Telefono secundario:</strong>
    <%= usuario.tlf_secundario %>
  </p>

</div>
<center>

app/views/usuarios/edit.html.erb
<h1>Modificar Usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Volver a usuario", @usuario %> |
  <%= link_to "Ir a lista de usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bienvenido al Listado de usuarios de Sisco Bank C.A.</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Ver Usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "Agregar Usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Agregar Usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Volver a Listado", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Modificar usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Volver a lista de usuarios", usuarios_path %>

  <%= button_to "Eliminar usuario", @usuario, method: :delete %>
</div>